// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// import.rs
// Import workspace information.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct ImportCommand;

impl ImportCommand {
    /// `workspace_file` - workspace file., required, value_name: WORKSPACE_FILE
    #[allow(unused_variables)]
    pub fn execute(&self, workspace_file: String) -> Result<()> {
        // TODO: Import workspace information.
        println!("Command `import` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for ImportCommand {
    fn name(&self) -> &'static str {
        "import"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let workspace_file = matches
            .get_one::<String>("workspace_file")
            .ok_or_else(|| anyhow!("Missing required argument: workspace_file"))?
            .clone();
        self.execute(workspace_file)
    }
}
