// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// list.rs
// List all workspaces.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct ListCommand;

impl ListCommand {
    #[allow(unused_variables)]
    fn execute(&self) -> Result<()> {
        // TODO: List all workspaces.
        println!("Command `list` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for ListCommand {
    fn name(&self) -> &'static str {
        "list"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
