// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// checksum.rs
// Get checksum of remote file (SHA256).
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct ChecksumCommand;

impl ChecksumCommand {
    /// `file` - Remote file to check. NO FOLDERS!, required, value_name: FILE
    #[allow(unused_variables)]
    pub fn execute(&self, file: String) -> Result<()> {
        // TODO: Get checksum of remote file (SHA256).
        println!("Command `checksum` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for ChecksumCommand {
    fn name(&self) -> &'static str {
        "checksum"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let file = matches
            .get_one::<String>("file")
            .ok_or_else(|| anyhow!("Missing required argument: file"))?
            .clone();
        self.execute(file)
    }
}
