// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// create_freq.rs
// Create a new frequency channel
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct CreateFreqCommand;

impl CreateFreqCommand {
    /// `freq` - New frequency unique id, required, value_name: FREQ_ID
    /// `p` - Create frequency with password
    /// `max_people` - Max online user limit, value_name: NUM
    #[allow(unused_variables)]
	pub fn execute(&self, freq: String, p: bool, max_people: Option<String>) -> Result<()> {
		// TODO: Create a new frequency channel
		println!("Command `create_freq` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for CreateFreqCommand {
	fn name(&self) -> &'static str {
		"create_freq"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        let freq = matches
            .get_one::<String>("freq")
            .ok_or_else(|| anyhow!("Missing required argument: freq"))?
            .clone();
        let p = matches.get_flag("p");
        let max_people = matches
            .get_one::<String>("max_people")
            .cloned();
        self.execute(freq, p, max_people)
	}
}
