// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// disconnect.rs
// Disconnect from server
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct DisconnectCommand;

impl DisconnectCommand {
    #[allow(unused_variables)]
	pub fn execute(&self) -> Result<()> {
		// TODO: Disconnect from server
		println!("Command `disconnect` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for DisconnectCommand {
	fn name(&self) -> &'static str {
		"disconnect"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
	}
}
