// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// file_info.rs
// Get remote file infomation.
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct FileInfoCommand;

impl FileInfoCommand {
    /// `file` - The remote file, required, value_name: FILE
    #[allow(unused_variables)]
    pub fn execute(&self, file: String) -> Result<()> {
        // TODO: Get remote file infomation.
        println!("Command `file_info` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for FileInfoCommand {
    fn name(&self) -> &'static str {
        "file_info"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let file = matches
            .get_one::<String>("file")
            .ok_or_else(|| anyhow!("Missing required argument: file"))?
            .clone();
        self.execute(file)
    }
}
