// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// foreground.rs
// Switch to session if there is only one.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct ForegroundCommand;

impl ForegroundCommand {
    #[allow(unused_variables)]
	pub fn execute(&self) -> Result<()> {
		// TODO: Switch to session if there is only one.
		println!("Command `foreground` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for ForegroundCommand {
	fn name(&self) -> &'static str {
		"foreground"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
	}
}
