// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// freq_info.rs
// Get frequency information
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct FreqInfoCommand;

impl FreqInfoCommand {
    /// `frequency` - freq ID, required, value_name: FREQ
    #[allow(unused_variables)]
	pub fn execute(&self, frequency: String) -> Result<()> {
		// TODO: Get frequency information
		println!("Command `freq_info` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for FreqInfoCommand {
	fn name(&self) -> &'static str {
		"freq_info"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        let frequency = matches
            .get_one::<String>("frequency")
            .ok_or_else(|| anyhow!("Missing required argument: frequency"))?
            .clone();
        self.execute(frequency)
	}
}
