// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// kick.rs
// kick user from freq (op)
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct KickCommand;

impl KickCommand {
    /// `user` - the full username, e.g., HZFY@192.168.78.91, required, value_name: USER
    #[allow(unused_variables)]
    pub fn execute(&self, user: String) -> Result<()> {
        // TODO: kick user from freq (op)
        println!("Command `kick` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for KickCommand {
    fn name(&self) -> &'static str {
        "kick"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let user = matches
            .get_one::<String>("user")
            .ok_or_else(|| anyhow!("Missing required argument: user"))?
            .clone();
        self.execute(user)
    }
}
