// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// leave_freq.rs
// Leave current frequency.
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct LeaveFreqCommand;

impl LeaveFreqCommand {
    #[allow(unused_variables)]
    pub fn execute(&self) -> Result<()> {
        // TODO: Leave current frequency.
        println!("Command `leave_freq` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for LeaveFreqCommand {
    fn name(&self) -> &'static str {
        "leave_freq"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
