// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// pwd.rs
// Get current remote directory.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct PwdCommand;

impl PwdCommand {
    #[allow(unused_variables)]
	pub fn execute(&self) -> Result<()> {
		// TODO: Get current remote directory.
		println!("Command `pwd` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for PwdCommand {
	fn name(&self) -> &'static str {
		"pwd"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
	}
}
