// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// route.rs
// Trace route to server
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct RouteCommand;

impl RouteCommand {
    #[allow(unused_variables)]
	pub fn execute(&self) -> Result<()> {
		// TODO: Trace route to server
		println!("Command `route` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for RouteCommand {
	fn name(&self) -> &'static str {
		"route"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
	}
}
