// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// set.rs
// Set session options
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct SetCommand;

impl SetCommand {
    /// `key` - Session config key, required, value_name: KEY
    /// `value` - Session config value, required, value_name: VALUE
    #[allow(unused_variables)]
	pub fn execute(&self, key: String, value: String) -> Result<()> {
		// TODO: Set session options
		println!("Command `set` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for SetCommand {
	fn name(&self) -> &'static str {
		"set"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        let key = matches
            .get_one::<String>("key")
            .ok_or_else(|| anyhow!("Missing required argument: key"))?
            .clone();
        let value = matches
            .get_one::<String>("value")
            .ok_or_else(|| anyhow!("Missing required argument: value"))?
            .clone();
        self.execute(key, value)
	}
}
