// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// trop.rs
// transfer creator permission.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct TropCommand;

impl TropCommand {
    /// `user` - the full username, e.g., HZFY@192.168.78.91, required, value_name: USER
    #[allow(unused_variables)]
	pub fn execute(&self, user: String) -> Result<()> {
		// TODO: transfer creator permission.
		println!("Command `trop` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for TropCommand {
	fn name(&self) -> &'static str {
		"trop"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        let user = matches
            .get_one::<String>("user")
            .ok_or_else(|| anyhow!("Missing required argument: user"))?
            .clone();
        self.execute(user)
	}
}
