// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// unset.rs
// Unset session variable.
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct UnsetCommand;

impl UnsetCommand {
    /// `key` - Config key name, value_name: KEY
    /// `all` - Clear all session options.
    #[allow(unused_variables)]
    pub fn execute(&self, key: Option<String>, all: bool) -> Result<()> {
        // TODO: Unset session variable.
        println!("Command `unset` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for UnsetCommand {
    fn name(&self) -> &'static str {
        "unset"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let key = matches.get_one::<String>("key").cloned();
        let all = matches.get_flag("all");
        self.execute(key, all)
    }
}
