[workspace]
members = [
    "crates/cli-core",
    "crates/cli",
    "crates/srv", 
	"crates/plugins/werewolf", 
	"crates/plugins/translations", 
	"crates/plugins/ai-glm", 
    "crates/helper/cmd-gen",
    "crates/sl-rs",
    "crates/neo-lolcat", 
    "crates/protos",
    "crates/edit/crates/*", 
    "crates/plugins/cli-standard", 
    "crates/helper/yaml2cmd-build",
    "crates/helper/yaml2cmd", 
    "crates/helper/hook_macro",
    "crates/cli-core-types",
    "crates/helper/which_dylib",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.93"
version = "0.1.0"
authors = ["HZFY"]

[profile.release]
opt-level = 3
codegen-units = 1

[workspace.dependencies]
edit = { path = "./crates/edit/crates/edit" }
lsh = { path = "./crates/edit/crates/lsh" }
stdext = { path = "./crates/edit/crates/stdext" }
unicode-gen = { path = "./crates/edit/crates/unicode-gen" }
cli-core-types = { path = "./crates/cli-core-types" }
yaml2cmd-build = { path = "./crates/helper/yaml2cmd-build" }
sl-rs = { path = "./crates/sl-rs" }
lolcat = { path = "./crates/neo-lolcat" }
protos = { path = "./crates/protos" }
yaml2cmd = { path = "./crates/helper/yaml2cmd" }
hook_macro = { path = "./crates/helper/hook_macro" }
which_dylib = { path = "./crates/helper/which_dylib" }
prost = "0.13"
# prost-types = "0.14"
tonic = "0.12"
tonic-build = "0.12"
tokio = { version = "1", features = ["full"] }
libloading = "0.9.0"
safer-ffi = "0.2.0-rc1"
clap = "4"
anyhow = "1.0.103"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.0"

[workspace.lints.clippy]
missing_safety_doc = "allow"
