[workspace]
members = [
    "crates/cli-core",
    "crates/cli",
    "crates/srv", 
	"crates/plugins/werewolf", 
	"crates/plugins/translations", 
	"crates/plugins/ai-glm", 
    "crates/helper/cmd-gen",
    "crates/sl-rs",
    "crates/neo-lolcat", "crates/protos",
]
resolver = "2"

[profile.release]
opt-level = 3
codegen-units = 1
