[workspace]
members = [
    "crates/cli-core",
    "crates/cli",
    "crates/srv", 
	"crates/plugins/werewolf", 
	"crates/plugins/translations", 
	"crates/plugins/ai-glm", 
    "crates/helper/cmd-gen",
    "crates/sl-rs",
    "crates/neo-lolcat", 
    "crates/protos",
    "crates/edit/crates/*",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.93"
version = "0.1.0"
authors = ["HZFY"]

[profile.release]
opt-level = 3
codegen-units = 1

[workspace.dependencies]
edit = { path = "./crates/edit/crates/edit" }
lsh = { path = "./crates/edit/crates/lsh" }
stdext = { path = "./crates/edit/crates/stdext" }
unicode-gen = { path = "./crates/edit/crates/unicode-gen" }