// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// cd.rs
// Change the current remote directory to DIR.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct CdCommand;

impl CdCommand {
    /// `dir` - DIR to change., required, value_name: DIR
    #[allow(unused_variables)]
    pub fn execute(&self, dir: String) -> Result<()> {
        // TODO: Change the current remote directory to DIR.
        println!("Command `cd` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for CdCommand {
    fn name(&self) -> &'static str {
        "cd"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let dir = matches
            .get_one::<String>("dir")
            .ok_or_else(|| anyhow!("Missing required argument: dir"))?
            .clone();
        self.execute(dir)
    }
}
