// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// disband.rs
// disband current frequency.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct DisbandCommand;

impl DisbandCommand {
    #[allow(unused_variables)]
    fn execute(&self) -> Result<()> {
        // TODO: disband current frequency.
        println!("Command `disband` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for DisbandCommand {
    fn name(&self) -> &'static str {
        "disband"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
