// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// feedback.rs
// Send feedback.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct FeedbackCommand;

impl FeedbackCommand {
    /// `content` - Your feedback content. fallbacks to editor.
    #[allow(unused_variables)]
    pub fn execute(&self, content: Option<String>) -> Result<()> {
        // TODO: Send feedback.
        println!("Command `feedback` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for FeedbackCommand {
    fn name(&self) -> &'static str {
        "feedback"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let content = matches.get_one::<String>("content").cloned();
        self.execute(content)
    }
}
