// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// join_freq.rs
// Join a target frequency channel
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct JoinFreqCommand;

impl JoinFreqCommand {
    /// `freq` - Target frequency id, required, value_name: FREQ_ID
    #[allow(unused_variables)]
    pub fn execute(&self, freq: String) -> Result<()> {
        // TODO: Join a target frequency channel
        println!("Command `join_freq` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for JoinFreqCommand {
    fn name(&self) -> &'static str {
        "join_freq"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let freq = matches
            .get_one::<String>("freq")
            .ok_or_else(|| anyhow!("Missing required argument: freq"))?
            .clone();
        self.execute(freq)
    }
}
