// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// msg.rs
// send message
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct MsgCommand;

impl MsgCommand {
    /// `message` - Your message, fallback to editor
    /// `users` - The users, default everybody., value_name: USERS
    #[allow(unused_variables)]
    fn execute(&self, message: Option<String>, users: Vec<String>) -> Result<()> {
        // TODO: send message
        println!("Command `msg` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for MsgCommand {
    fn name(&self) -> &'static str {
        "msg"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let message = matches.get_one::<String>("message").cloned();
        let users = matches
            .get_many::<String>("users")
            .unwrap_or_default().cloned()
            .collect::<Vec<_>>();
        self.execute(message, users)
    }
}
