// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// reply.rs
// Reply to the user who has just spoken quickly
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct ReplyCommand;

impl ReplyCommand {
    /// `message` - Your message, if not given, fallback to editor mode.
    #[allow(unused_variables)]
    pub fn execute(&self, message: Option<String>) -> Result<()> {
        // TODO: Reply to the user who has just spoken quickly
        println!("Command `reply` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for ReplyCommand {
    fn name(&self) -> &'static str {
        "reply"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let message = matches.get_one::<String>("message").cloned();
        self.execute(message)
    }
}
