// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// tasks.rs
// Get scheduled tasks.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct TasksCommand;

impl TasksCommand {
    #[allow(unused_variables)]
    fn execute(&self) -> Result<()> {
        // TODO: Get scheduled tasks.
        println!("Command `tasks` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for TasksCommand {
    fn name(&self) -> &'static str {
        "tasks"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
