// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// unignore.rs
// Unignore comments of certain user
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct UnignoreCommand;

impl UnignoreCommand {
    /// `user` - the full username, e.g., HZFY@192.168.78.91, required, value_name: USER
    #[allow(unused_variables)]
    fn execute(&self, user: String) -> Result<()> {
        // TODO: Unignore comments of certain user
        println!("Command `unignore` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for UnignoreCommand {
    fn name(&self) -> &'static str {
        "unignore"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let user = matches
            .get_one::<String>("user")
            .ok_or_else(|| anyhow!("Missing required argument: user"))?
            .clone();
        self.execute(user)
    }
}
