[package]
name = "cli"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "MIT"

[dependencies]
clap = "4"
shell-words = "1.1.1"
rustyline = "14"
cli_core = { path = "../cli-core" }
clap_complete = { version = "4", features = ["unstable-dynamic"] }
anyhow = "1.0.103"
sha2 = "0.10"
base64 = "0.22.1"
humantime = "2.1"
ctrlc = "3.4"
libc = "0.2.186"
rpassword = "7.5.4"
sl-rs = { path = "../sl-rs" }

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.0"
built = { version = "0.7", features = [
    "chrono",
    "git2",
    "dependency-tree"
] }
