use check_keyword::CheckKeyword;
use serde::Deserialize;
use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

const AUTO_GENERATED_TAG: &str = "// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.";

#[derive(Debug, Deserialize)]
struct Config {
    commands: Vec<CommandDef>,
}

#[derive(Debug, Deserialize)]
struct CommandDef {
    name: String,
    about: String,

    #[serde(default)]
    debug_only: bool,

    #[serde(default)]
    subcommands: Vec<CommandDef>,

    // 新增：支持 args 字段
    #[serde(default)]
    args: Vec<ArgDef>,
}

#[derive(Debug, Deserialize)]
struct ArgDef {
    name: String,
    // #[serde(default)]
    // short: Option<char>,
    // #[serde(default)]
    // long: Option<String>,
    #[serde(default)]
    help: Option<String>,
    #[serde(default)]
    value_name: Option<String>,
    #[serde(default)]
    required: bool,
    #[serde(default)]
    num_args: Option<String>,
    #[serde(default)]
    action: Option<String>,
    #[serde(default)]
    default_value: Option<String>,
    #[serde(default)]
    conflicts_with: Option<String>,
    #[serde(default)]
    value_parser: Option<String>,
}

/// 把命令名转成 Rust 结构体名
/// setg → Setg
/// create_freq → CreateFreq
fn to_struct_name(name: &str) -> String {
    name.split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<String>()
        + "Command"
}

/// 检查文件是否包含自动生成的标记（即未被手动修改）
fn is_file_unmodified(path: &Path) -> bool {
    if !path.exists() {
        return false;
    }
    if let Ok(content) = fs::read_to_string(path)
        && let Some(first_line) = content.lines().next()
    {
        return first_line.trim() == AUTO_GENERATED_TAG;
    }
    false
}

/// 判断文件是否需要更新
fn should_update_file(path: &Path, content: &str) -> Option<bool> {
    if !path.exists() {
        return Some(true); // 文件不存在，需要创建
    }

    if is_file_unmodified(path) {
        // 文件包含标记，检查内容是否相同
        if let Ok(current_content) = fs::read_to_string(path)
            && current_content == content
        {
            return Some(false); // 内容相同，不需要更新
        }
        return Some(true); // 内容不同，可以安全覆盖
    }

    // 文件存在但没有标记或被手动修改过
    None // 返回 None 表示被用户修改
}

/// 生成单个命令模块（带 execute 方法和变量提取）
fn generate_module(name: &str, about: &str, debug_only: bool, args: &[ArgDef]) -> String {
    let struct_name = to_struct_name(name);
    let cfg_attr = if debug_only { "#[cfg(debug_assertions)]\n" } else { "" };

    // 把 about 转成 Rust 注释
    let comment_lines: Vec<&str> = about.lines().collect();
    let comment =
        comment_lines.iter().map(|line| format!("// {}", line)).collect::<Vec<_>>().join("\n");

    // 构建 execute 方法的参数和文档注释
    let mut execute_params = Vec::new();
    let mut doc_comments = Vec::new();
    let mut extract_vars = Vec::new();
    let mut execute_call_args = Vec::new();

    for arg in args {
        // 确定参数类型
        let param_type = if let Some(vp) = &arg.value_parser {
            vp.clone()
        } else if let Some(action) = &arg.action {
            match action.as_str() {
                "set_true" | "set_false" => "bool".to_string(),
                "count" => "u8".to_string(),
                _ => "String".to_string(),
            }
        } else {
            "String".to_string()
        };
        let is_num_args =
            arg.num_args.as_deref() == Some("0..") || arg.num_args.as_deref() == Some("0..=");

        let param_type1 =
            if is_num_args { format!("Vec<{}>", param_type) } else { param_type.clone() };

        // 生成文档注释
        let mut doc_parts = Vec::new();

        // 基础描述
        if let Some(help) = &arg.help {
            let normalized = help.replace("\r\n", " ").replace('\n', " ");
            doc_parts.push(normalized);
        }

        // 必要信息
        if arg.required {
            doc_parts.push("required".to_string());
        }

        // value_name
        if let Some(vn) = &arg.value_name {
            doc_parts.push(format!("value_name: {}", vn));
        }

        // default_value
        if let Some(dv) = &arg.default_value {
            doc_parts.push(format!("default: {}", dv));
        }

        // conflicts_with
        if let Some(cf) = &arg.conflicts_with {
            doc_parts.push(format!("conflicts with: {}", cf));
        }

        let doc = if doc_parts.is_empty() {
            format!("    /// `{}`", arg.name)
        } else {
            format!("    /// `{}` - {}", arg.name, doc_parts.join(", "))
        };

        doc_comments.push(doc);

        // 生成提取变量的代码
        let extract = if let Some(action) = &arg.action {
            match action.as_str() {
                "set_true" => {
                    format!("        let {} = matches.get_flag(\"{}\");", arg.name, arg.name)
                }
                "set_false" => {
                    format!("        let {} = !matches.get_flag(\"{}\");", arg.name, arg.name)
                }
                "count" => {
                    format!("        let {} = matches.get_count(\"{}\");", arg.name, arg.name)
                }
                _ => {
                    if arg.required {
                        format!(
                            "        let {} = matches\n            .get_one::<{}>(\"{}\")\n            .ok_or_else(|| anyhow!(\"Missing required argument: {}\"))?\n            .clone();",
                            arg.name, param_type, arg.name, arg.name
                        )
                    } else {
                        format!(
                            "        let {} = matches\n            .get_one::<{}>(\"{}\")\n            .cloned();",
                            arg.name, param_type, arg.name
                        )
                    }
                }
            }
        } else if is_num_args {
            format!(
                "        let {} = matches\n            .get_many::<{}>(\"{}\")\n            .unwrap_or_default()\n            .map(|s| s.clone())\n            .collect::<Vec<_>>();",
                arg.name, param_type, arg.name
            )
        } else if arg.required {
            format!(
                "        let {} = matches\n            .get_one::<{}>(\"{}\")\n            .ok_or_else(|| anyhow!(\"Missing required argument: {}\"))?\n            .clone();",
                arg.name, param_type, arg.name, arg.name
            )
        } else {
            format!(
                "        let {} = matches\n            .get_one::<{}>(\"{}\")\n            .cloned();",
                arg.name, param_type, arg.name
            )
        };
        extract_vars.push(extract);

        // 生成 execute 参数
        if arg.required
            || arg.num_args.is_some()
            || matches!(arg.action.as_deref(), Some("set_true" | "set_false" | "count"))
        {
            execute_params.push(format!("{}: {}", arg.name, param_type1));
        } else {
            execute_params.push(format!("{}: Option<{}>", arg.name, param_type1));
        }
        execute_call_args.push(arg.name.clone());
    }

    // 组装 execute 方法签名
    let execute_sig = if execute_params.is_empty() {
        "\tpub fn execute(&self) -> Result<()>".to_string()
    } else {
        format!("\tpub fn execute(&self, {}) -> Result<()>", execute_params.join(", "))
    };

    // 组装 execute 调用
    let execute_call = if execute_call_args.is_empty() {
        "self.execute()".to_string()
    } else {
        format!("self.execute({})", execute_call_args.join(", "))
    };

    // 生成完整的模块代码
    let mut code = String::new();
    code.push_str(&format!(
        "{AUTO_GENERATED_TAG}\n\
         {cfg_attr}// {name}.rs\n\
         {comment}\n\
         #[allow(unused_imports)]\n\
         use crate::INTERRUPTED;\n\
         use crate::commands::CommandExecutor;\n\
         #[allow(unused_imports)]\n\
         use anyhow::{{anyhow, Result}};\n\
         use clap::ArgMatches;\n\
         \n\
         pub struct {struct_name};\n\
         \n\
         impl {struct_name} {{\n"
    ));

    // 添加文档注释
    for doc in &doc_comments {
        code.push_str(&format!("{}\n", doc));
    }
    // 生成 TODO 注释（多行）
    let todo_lines: Vec<String> =
        comment_lines.iter().map(|line| format!("\t\t// TODO: {}", line)).collect();
    let todo_block = todo_lines.join("\n");

    code.push_str(&format!(
        "    #[allow(unused_variables)]\n\
  {} {{\n\
{todo_block}\n\
      \t\tprintln!(\"Command `{name}` is not yet implemented.\");\n\
      \t\tOk(())\n\
  \t}}\n\
  }}\n\
  \n\
  impl CommandExecutor for {struct_name} {{\n\
      \tfn name(&self) -> &'static str {{\n\
          \t\t\"{name}\"\n\
      \t}}\n\
      \n\
      \t#[allow(unused_variables)]\n\
      \tfn run(&self, matches: &ArgMatches) -> Result<()> {{\n",
        execute_sig,
        todo_block = todo_block,
        name = name,
    ));

    // 添加变量提取代码
    for extract in &extract_vars {
        code.push_str(&format!("{}\n", extract));
    }

    code.push_str(&format!(
        "        {}\n\
         \t}}\n\
         }}\n",
        execute_call
    ));

    code
}

/// 递归处理命令及其 subcommands
fn process_commands(
    cmds: &[CommandDef],
    parent_dir: &Path,
    mod_entries: &mut Vec<(String, bool)>,
    prefix: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    for cmd in cmds {
        let current_prefix =
            if prefix.is_empty() { cmd.name.clone() } else { format!("{}::{}", prefix, cmd.name) };

        let file_name = format!("{}.rs", cmd.name);
        let file_path = parent_dir.join(&file_name);

        if !cmd.subcommands.is_empty() {
            let sub_dir = parent_dir.join(&cmd.name);
            if !sub_dir.exists() {
                fs::create_dir_all(&sub_dir)?;
                println!("[MKDIR] {}", sub_dir.display());
            }

            mod_entries.push((current_prefix.clone(), true));

            process_commands(&cmd.subcommands, &sub_dir, mod_entries, &current_prefix)?;
        } else {
            let content = generate_module(&cmd.name, &cmd.about, cmd.debug_only, &cmd.args);

            match should_update_file(&file_path, &content) {
                Some(true) => {
                    let mut f = File::create(&file_path)?;
                    f.write_all(content.as_bytes())?;

                    if !file_path.exists() {
                        println!("[CREATE] {}", file_name);
                    } else {
                        println!("[UPDATE] {}", file_name);
                    }
                }
                Some(false) => {
                    println!("[SKIP] {} (up-to-date)", file_name);
                }
                None => {
                    println!("[SKIP] {} (modified by user)", file_name);
                }
            }

            mod_entries.push((current_prefix, false));
        }
    }
    Ok(())
}

/// 生成子命令列表的 all_commands 部分
fn generate_sub_all_commands(cmd: &CommandDef, indent: usize) -> String {
    let mut result = String::new();
    let indent_str = " ".repeat(indent);

    for sub in &cmd.subcommands {
        if sub.debug_only {
            result.push_str(&format!("{}#[cfg(debug_assertions)]\n", indent_str));
        }

        let struct_name = to_struct_name(&sub.name);
        result.push_str(&format!(
            "{}Arc::new({}::{}),\n",
            indent_str,
            sub.name.clone().into_safe(),
            struct_name
        ));
    }

    result
}

/// 收集所有预期的文件路径
fn collect_expected_files(cmds: &[CommandDef], base_dir: &Path, expected_files: &mut Vec<String>) {
    for cmd in cmds {
        if cmd.subcommands.is_empty() {
            let file_path = base_dir.join(format!("{}.rs", cmd.name));
            expected_files.push(file_path.to_string_lossy().to_string());
        } else {
            let sub_dir = base_dir.join(&cmd.name);
            let mod_rs_path = sub_dir.join("mod.rs");
            expected_files.push(mod_rs_path.to_string_lossy().to_string());
            collect_expected_files(&cmd.subcommands, &sub_dir, expected_files);
        }
    }
}

/// 清理不再需要的文件
fn cleanup_orphaned_files(expected_files: &[String]) -> Result<(), Box<dyn std::error::Error>> {
    let commands_dir = Path::new("./crates/cli-core/src/commands");

    // 遍历所有 .rs 文件
    fn visit_dirs(dir: &Path, expected_files: &[String]) -> Result<(), Box<dyn std::error::Error>> {
        if dir.exists() {
            for entry in fs::read_dir(dir)? {
                let entry = entry?;
                let path = entry.path();

                if path.is_dir() {
                    visit_dirs(&path, expected_files)?;
                } else if path.extension().and_then(|s| s.to_str()) == Some("rs") {
                    let path_str = path.to_string_lossy().to_string();
                    if !expected_files.contains(&path_str) {
                        // 检查是否是自动生成的文件（包含标记）
                        if is_file_unmodified(&path) {
                            fs::remove_file(&path)?;
                            println!("[DELETE] {}", path.file_name().unwrap().to_string_lossy());
                        } else {
                            println!(
                                "[SKIP] {} (modified by user, not deleted)",
                                path.file_name().unwrap().to_string_lossy()
                            );
                        }
                    }
                }
            }
        }
        Ok(())
    }

    visit_dirs(commands_dir, expected_files)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();

    let yaml_path = Path::new(&manifest)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("cli-core")
        .join("commands.yaml");
    println!("{}", yaml_path.display());

    if !yaml_path.exists() {
        eprintln!("❌ commands.yaml not found in current directory");
        std::process::exit(1);
    }

    let yaml = fs::read_to_string(&yaml_path)?;
    let config: Config = serde_yaml::from_str(&yaml)?;

    let out_dir = Path::new("./crates/cli-core/src/commands");
    if !out_dir.exists() {
        fs::create_dir_all(out_dir)?;
    }

    let mut mod_entries = Vec::new();

    process_commands(&config.commands, out_dir, &mut mod_entries, "")?;

    // 收集所有预期文件
    let mut expected_files = Vec::new();
    // 添加 mod.rs 到预期文件
    expected_files.push(out_dir.join("mod.rs").to_string_lossy().to_string());
    collect_expected_files(&config.commands, out_dir, &mut expected_files);

    // 为有子命令的命令添加 mod.rs
    for cmd in &config.commands {
        if !cmd.subcommands.is_empty() {
            let sub_dir = out_dir.join(&cmd.name);
            let mod_rs_path = sub_dir.join("mod.rs");
            expected_files.push(mod_rs_path.to_string_lossy().to_string());
        }
    }

    // 清理孤立文件
    cleanup_orphaned_files(&expected_files)?;

    // 生成 mod.rs - 主入口
    let mut mod_rs = String::new();
    mod_rs.push_str(&format!(
        "{AUTO_GENERATED_TAG}\n\
         use clap::ArgMatches;\n\
         use std::sync::Arc;\n\
         #[allow(unused_imports)]\n\
         use anyhow::{{anyhow, Result}};\n\
         use std::sync::atomic::Ordering;\n\
         use crate::INTERRUPTED;\n\
         \n\
         pub trait CommandExecutor {{\n\
             fn name(&self) -> &'static str;\n\
             \n\
             fn run(&self, matches: &ArgMatches) -> Result<()>;\n\
         }}\n"
    ));

    // 生成顶级模块声明
    for (entry, _) in &mod_entries {
        let parts: Vec<&str> = entry.split("::").collect();

        if parts.len() == 1 {
            let cmd_name = &parts[0];

            fn find_cmd<'a>(cmds: &'a [CommandDef], name: &str) -> Option<&'a CommandDef> {
                cmds.iter().find(|c| c.name == name)
            }

            let cmd = find_cmd(&config.commands, cmd_name);

            if let Some(cmd) = cmd
                && cmd.debug_only
            {
                mod_rs.push_str("#[cfg(debug_assertions)]\n");
            }

            mod_rs.push_str(&format!("pub mod {};\n", cmd_name.to_string().into_safe()));
        }
    }

    mod_rs.push('\n');
    mod_rs.push_str("pub fn all_commands() -> Vec<Arc<dyn CommandExecutor>> {\n");
    mod_rs.push_str("    vec![\n");

    for (entry, _has_sub) in &mod_entries {
        if entry.contains("::") {
            continue;
        }

        let parts: Vec<&str> = entry.split("::").collect();
        let cmd_name = parts[parts.len() - 1];

        fn find_cmd<'a>(cmds: &'a [CommandDef], name: &str) -> Option<&'a CommandDef> {
            cmds.iter().find(|c| c.name == name)
        }

        let cmd = find_cmd(&config.commands, cmd_name);

        if let Some(cmd) = cmd
            && cmd.debug_only
        {
            mod_rs.push_str("        #[cfg(debug_assertions)]\n");
        }

        let struct_name = to_struct_name(cmd_name);
        mod_rs.push_str(&format!(
            "        Arc::new({}::{}),\n",
            cmd_name.to_string().into_safe(),
            struct_name
        ));
    }

    mod_rs.push_str("    ]\n");
    mod_rs.push_str("}\n");

    mod_rs.push_str(
        r#"
pub fn dispatch(matches: &ArgMatches) -> Result<()> {
    for cmd in all_commands() {
        if let Some(sub_matches) = matches.subcommand_matches(cmd.name()) {
            INTERRUPTED.store(false, Ordering::SeqCst);
            return cmd.run(sub_matches);
        }
    }
    eprintln!("No matching command found. Use --help for usage information.");
    Ok(())
}
"#,
    );

    // 检查 mod.rs 是否需要更新
    let mod_rs_path = out_dir.join("mod.rs");
    match should_update_file(&mod_rs_path, &mod_rs) {
        Some(true) => {
            fs::write(&mod_rs_path, &mod_rs)?;
            if !mod_rs_path.exists() {
                println!("[CREATE] mod.rs (top-level)");
            } else {
                println!("[UPDATE] mod.rs (top-level)");
            }
        }
        Some(false) => {
            println!("[SKIP] mod.rs (top-level, up-to-date)");
        }
        None => {
            println!("[SKIP] mod.rs (top-level, modified by user)");
        }
    }

    // 为有子命令的文件夹生成内部的 mod.rs
    for (entry, has_sub) in &mod_entries {
        if *has_sub {
            let parts: Vec<&str> = entry.split("::").collect();
            let dir_name = parts.last().unwrap();

            let mut dir_path = out_dir.to_path_buf();
            for part in &parts {
                dir_path = dir_path.join(part);
            }

            let mut sub_mod_rs = String::new();
            sub_mod_rs.push_str(&format!("{AUTO_GENERATED_TAG}\n"));

            fn find_cmd_by_path<'a>(
                cmds: &'a [CommandDef],
                parts: &[&str],
            ) -> Option<&'a CommandDef> {
                if parts.is_empty() {
                    return None;
                }
                let cmd = cmds.iter().find(|c| c.name == parts[0])?;
                if parts.len() == 1 {
                    Some(cmd)
                } else {
                    find_cmd_by_path(&cmd.subcommands, &parts[1..])
                }
            }

            let cmd = find_cmd_by_path(&config.commands, &parts);

            if let Some(cmd) = cmd {
                sub_mod_rs.push_str("use clap::ArgMatches;\n");
                sub_mod_rs.push_str("use std::sync::Arc;\n");
                sub_mod_rs.push_str("#[allow(unused_imports)]\n");
                sub_mod_rs.push_str("use anyhow::{anyhow, Result};\n");
                sub_mod_rs.push_str("use crate::commands::CommandExecutor;\n");
                sub_mod_rs.push_str("use crate::INTERRUPTED;\n");
                sub_mod_rs.push_str("use std::sync::atomic::Ordering;\n\n");

                let parent_struct_name = to_struct_name(dir_name);
                sub_mod_rs.push_str(&format!(
                    r#"pub struct {parent_struct_name};

impl CommandExecutor for {parent_struct_name} {{
    fn name(&self) -> &'static str {{
        "{dir_name}"
    }}

    fn run(&self, matches: &ArgMatches) -> Result<()> {{
        dispatch(matches)
    }}
}}

"#,
                    parent_struct_name = parent_struct_name,
                    dir_name = dir_name,
                ));

                for sub in &cmd.subcommands {
                    if sub.debug_only {
                        sub_mod_rs.push_str("#[cfg(debug_assertions)]\n");
                    }

                    sub_mod_rs.push_str(&format!("pub mod {};\n", sub.name.clone().into_safe()));
                }

                sub_mod_rs.push_str(&format!(
                    r#"
pub fn all_commands() -> Vec<Arc<dyn CommandExecutor>> {{
    vec![
{}
    ]
}}

"#,
                    generate_sub_all_commands(cmd, 8)
                ));

                sub_mod_rs.push_str("pub fn dispatch(matches: &ArgMatches) -> Result<()> {\n");
                sub_mod_rs.push_str("    for cmd in all_commands() {\n");
                sub_mod_rs.push_str(
                    "        if let Some(sub_matches) = matches.subcommand_matches(cmd.name()) {\n",
                );
                sub_mod_rs.push_str("            INTERRUPTED.store(false, Ordering::SeqCst);\n");
                sub_mod_rs.push_str("            return cmd.run(sub_matches);\n");
                sub_mod_rs.push_str("        }\n");
                sub_mod_rs.push_str("    }\n");
                sub_mod_rs.push_str("    eprintln!(\"No matching command found. Use --help for usage information.\");\n");
                sub_mod_rs.push_str("    Ok(())\n");
                sub_mod_rs.push_str("}\n");
            }

            // 检查子 mod.rs 是否需要更新
            let sub_mod_rs_path = dir_path.join("mod.rs");
            match should_update_file(&sub_mod_rs_path, &sub_mod_rs) {
                Some(true) => {
                    fs::write(&sub_mod_rs_path, &sub_mod_rs)?;
                    if !sub_mod_rs_path.exists() {
                        println!("[CREATE] {}/mod.rs", dir_name);
                    } else {
                        println!("[UPDATE] {}/mod.rs", dir_name);
                    }
                }
                Some(false) => {
                    println!("[SKIP] {}/mod.rs (up-to-date)", dir_name);
                }
                None => {
                    println!("[SKIP] {}/mod.rs (modified by user)", dir_name);
                }
            }
        }
    }

    println!("\nDone! {} commands processed.", mod_entries.len());

    Ok(())
}
