use check_keyword::CheckKeyword;
use serde::Deserialize;
use std::collections::HashMap;
use std::collections::hash_map::DefaultHasher;
use std::env;
use std::fs::{self, File};
use std::hash::{Hash, Hasher};
use std::io::Write;
use std::path::Path;

#[derive(Debug, Deserialize)]
struct Config {
    commands: Vec<CommandDef>,
}

#[derive(Debug, Deserialize)]
struct CommandDef {
    name: String,
    about: String,

    #[serde(default)]
    debug_only: bool,

    #[serde(default)]
    subcommands: Vec<CommandDef>,

    // 新增：支持 args 字段
    #[serde(default)]
    args: Vec<ArgDef>,
}

#[derive(Debug, Deserialize)]
struct ArgDef {
    name: String,
    #[serde(default)]
    short: Option<char>,
    #[serde(default)]
    long: Option<String>,
    #[serde(default)]
    help: Option<String>,
    #[serde(default)]
    value_name: Option<String>,
    #[serde(default)]
    required: bool,
    #[serde(default)]
    num_args: Option<String>,
    #[serde(default)]
    action: Option<String>,
    #[serde(default)]
    default_value: Option<String>,
    #[serde(default)]
    conflicts_with: Option<String>,
    #[serde(default)]
    value_parser: Option<String>,
}

/// 把命令名转成 Rust 结构体名
/// setg → Setg
/// create_freq → CreateFreq
fn to_struct_name(name: &str) -> String {
    name.split('_')
        .map(|part| {
            let mut c = part.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<String>()
        + "Command"
}

/// 计算字符串的哈希值
fn hash_content(content: &str) -> u64 {
    let mut hasher = DefaultHasher::new();
    content.hash(&mut hasher);
    hasher.finish()
}

/// 读取 lock 文件
fn read_lock_file(path: &Path) -> HashMap<String, u64> {
    if !path.exists() {
        return HashMap::new();
    }
    let content = fs::read_to_string(path).unwrap_or_default();
    content
        .lines()
        .filter(|line| !line.trim_start().starts_with("//"))
        .filter_map(|line| {
            let mut parts = line.splitn(2, ':');
            let file_path = parts.next()?.trim().to_string();
            let hash = parts.next()?.trim().parse::<u64>().ok()?;
            Some((file_path, hash))
        })
        .collect()
}

/// 写入 lock 文件
fn write_lock_file(
    path: &Path,
    entries: &HashMap<String, u64>,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut content = String::from("// This file is automatically @generated by cmd-gen.\n");
    content.push_str("// It is not intended for manual editing.\n");

    let mut sorted_entries: Vec<_> = entries.iter().collect();
    sorted_entries.sort_by_key(|e| e.0.clone());

    for (file_path, hash) in sorted_entries {
        content.push_str(&format!("{}:{}\n", file_path, hash));
    }

    fs::write(path, content)?;
    Ok(())
}

/// 判断文件是否需要更新（基于 hash 校验）
fn should_update_file(path: &Path, content: &str, lock_entries: &HashMap<String, u64>) -> bool {
    let relative_path = path.to_string_lossy().to_string();
    let new_hash = hash_content(content);

    if !path.exists() {
        return true;
    }

    if let Some(&old_hash) = lock_entries.get(&relative_path) {
        if let Ok(current_content) = fs::read_to_string(path) {
            let current_hash = hash_content(&current_content);

            if current_hash == old_hash && current_hash != new_hash {
                // 文件未被手动修改且需要更新
                return true;
            } else if current_hash == new_hash {
                // 已经是最新
                return false;
            } else {
                // 文件被手动修改，跳过
                println!("[SKIP] {} (modified by user)", relative_path);
                return false;
            }
        }
    }

    true
}

/// 生成单个命令模块（带 execute 方法和变量提取）
fn generate_module(name: &str, about: &str, debug_only: bool, args: &[ArgDef]) -> String {
    let struct_name = to_struct_name(name);
    let cfg_attr = if debug_only { "#[cfg(debug_assertions)]\n" } else { "" };

    // 把 about 转成 Rust 注释
    let comment_lines: Vec<&str> = about.lines().collect();
    let comment =
        comment_lines.iter().map(|line| format!("// {}", line)).collect::<Vec<_>>().join("\n");

    // 构建 execute 方法的参数和文档注释
    let mut execute_params = Vec::new();
    let mut doc_comments = Vec::new();
    let mut extract_vars = Vec::new();
    let mut execute_call_args = Vec::new();

    for arg in args {
        // 确定参数类型
        let param_type = if let Some(vp) = &arg.value_parser {
            vp.clone()
        } else if let Some(action) = &arg.action {
            match action.as_str() {
                "set_true" | "set_false" => "bool".to_string(),
                "count" => "u8".to_string(),
                _ => "String".to_string(),
            }
        } else {
            "String".to_string()
        };
        let is_num_args =
            arg.num_args.as_deref() == Some("0..") || arg.num_args.as_deref() == Some("0..=");

        let param_type1 =
            if is_num_args { format!("Vec<{}>", param_type) } else { param_type.clone() };

        // 生成文档注释
        let mut doc_parts = Vec::new();

        // 基础描述
        if let Some(help) = &arg.help {
            let normalized = help.replace("\r\n", " ").replace('\n', " ");
            doc_parts.push(normalized);
        }

        // 必要信息
        if arg.required {
            doc_parts.push("required".to_string());
        }

        // value_name
        if let Some(vn) = &arg.value_name {
            doc_parts.push(format!("value_name: {}", vn));
        }

        // default_value
        if let Some(dv) = &arg.default_value {
            doc_parts.push(format!("default: {}", dv));
        }

        // conflicts_with
        if let Some(cf) = &arg.conflicts_with {
            doc_parts.push(format!("conflicts with: {}", cf));
        }

        let doc = if doc_parts.is_empty() {
            format!("    /// `{}`", arg.name)
        } else {
            format!("    /// `{}` - {}", arg.name, doc_parts.join(", "))
        };

        doc_comments.push(doc);

        // 生成提取变量的代码
        let extract = if let Some(action) = &arg.action {
            match action.as_str() {
                "set_true" => {
                    format!("        let {} = matches.get_flag(\"{}\");", arg.name, arg.name)
                }
                "set_false" => {
                    format!("        let {} = !matches.get_flag(\"{}\");", arg.name, arg.name)
                }
                "count" => {
                    format!("        let {} = matches.get_count(\"{}\");", arg.name, arg.name)
                }
                _ => {
                    if arg.required {
                        format!(
                            "        let {} = matches\n            .get_one::<{}>(\"{}\")\n            .ok_or_else(|| anyhow!(\"Missing required argument: {}\"))?\n            .clone();",
                            arg.name, param_type, arg.name, arg.name
                        )
                    } else {
                        format!(
                            "        let {} = matches\n            .get_one::<{}>(\"{}\")\n            .cloned();",
                            arg.name, param_type, arg.name
                        )
                    }
                }
            }
        } else if is_num_args {
            format!(
                "        let {} = matches\n            .get_many::<{}>(\"{}\")\n            .unwrap_or_default()\n            .map(|s| s.clone())\n            .collect::<Vec<_>>();",
                arg.name, param_type, arg.name
            )
        } else if arg.required {
            format!(
                "        let {} = matches\n            .get_one::<{}>(\"{}\")\n            .ok_or_else(|| anyhow!(\"Missing required argument: {}\"))?\n            .clone();",
                arg.name, param_type, arg.name, arg.name
            )
        } else {
            format!(
                "        let {} = matches\n            .get_one::<{}>(\"{}\")\n            .cloned();",
                arg.name, param_type, arg.name
            )
        };
        extract_vars.push(extract);

        // 生成 execute 参数
        if (arg.long.is_some() || arg.short.is_some()) && arg.required {
            execute_params.push(format!("{}: {}", arg.name, param_type1));
        } else if arg.required
            || arg.num_args.is_some()
            || matches!(arg.action.as_deref(), Some("set_true" | "set_false" | "count"))
        {
            execute_params.push(format!("{}: {}", arg.name, param_type1));
        } else {
            execute_params.push(format!("{}: Option<{}>", arg.name, param_type1));
        }
        execute_call_args.push(arg.name.clone());
    }

    // 组装 execute 方法签名
    let execute_sig = if execute_params.is_empty() {
        "\tfn execute(&self) -> Result<()>".to_string()
    } else {
        format!("\tfn execute(&self, {}) -> Result<()>", execute_params.join(", "))
    };

    // 组装 execute 调用
    let execute_call = if execute_call_args.is_empty() {
        "self.execute()".to_string()
    } else {
        format!("self.execute({})", execute_call_args.join(", "))
    };

    // 生成完整的模块代码
    let mut code = String::new();
    code.push_str(&format!(
        "{cfg_attr}// {name}.rs\n\
         {comment}\n\
         #[allow(unused_imports)]\n\
         use crate::INTERRUPTED;\n\
         use crate::commands::CommandExecutor;\n\
         #[allow(unused_imports)]\n\
         use anyhow::{{anyhow, Result}};\n\
         use clap::ArgMatches;\n\
         \n\
         pub struct {struct_name};\n\
         \n\
         impl {struct_name} {{\n"
    ));

    // 添加文档注释
    for doc in &doc_comments {
        code.push_str(&format!("{}\n", doc));
    }
    // 生成 TODO 注释（多行）
    let todo_lines: Vec<String> =
        comment_lines.iter().map(|line| format!("\t\t// TODO: {}", line)).collect();
    let todo_block = todo_lines.join("\n");

    code.push_str(&format!(
        "    #[allow(unused_variables)]\n\
  {} {{\n\
{todo_block}\n\
      \t\tprintln!(\"Command `{name}` is not yet implemented.\");\n\
      \t\tOk(())\n\
  \t}}\n\
  }}\n\
  \n\
  impl CommandExecutor for {struct_name} {{\n\
      \tfn name(&self) -> &'static str {{\n\
          \t\t\"{name}\"\n\
      \t}}\n\
      \n\
      \t#[allow(unused_variables)]\n\
      \tfn run(&self, matches: &ArgMatches) -> Result<()> {{\n",
        execute_sig,
        todo_block = todo_block,
        name = name,
    ));

    // 添加变量提取代码
    for extract in &extract_vars {
        code.push_str(&format!("{}\n", extract));
    }

    code.push_str(&format!(
        "        {}\n\
         \t}}\n\
         }}\n",
        execute_call
    ));

    code
}

/// 递归处理命令及其 subcommands
fn process_commands(
    cmds: &[CommandDef],
    parent_dir: &Path,
    mod_entries: &mut Vec<(String, bool)>,
    prefix: &str,
    lock_entries: &mut HashMap<String, u64>,
) -> Result<(), Box<dyn std::error::Error>> {
    for cmd in cmds {
        let current_prefix =
            if prefix.is_empty() { cmd.name.clone() } else { format!("{}::{}", prefix, cmd.name) };

        let file_name = format!("{}.rs", cmd.name);
        let file_path = parent_dir.join(&file_name);

        if !cmd.subcommands.is_empty() {
            let sub_dir = parent_dir.join(&cmd.name);
            if !sub_dir.exists() {
                fs::create_dir_all(&sub_dir)?;
                println!("[MKDIR] {}", sub_dir.display());
            }

            mod_entries.push((current_prefix.clone(), true));

            process_commands(
                &cmd.subcommands,
                &sub_dir,
                mod_entries,
                &current_prefix,
                lock_entries,
            )?;
        } else {
            let content = generate_module(&cmd.name, &cmd.about, cmd.debug_only, &cmd.args);
            let new_hash = hash_content(&content);

            if file_path.exists() {
                // 检查文件是否与锁中的哈希匹配
                let relative_path = file_path.to_string_lossy().to_string();
                let old_hash = lock_entries.get(&relative_path).copied();

                if let Some(old_hash) = old_hash {
                    // 读取当前文件内容并计算哈希
                    let current_content = fs::read_to_string(&file_path)?;
                    let current_hash = hash_content(&current_content);

                    if current_hash == old_hash && current_hash != new_hash {
                        // 文件未被修改且需要更新
                        let mut f = File::create(&file_path)?;
                        f.write_all(content.as_bytes())?;
                        println!("[UPDATE] {}", file_name);
                    } else if current_hash == new_hash {
                        println!("[SKIP] {}", file_name);
                    } else {
                        // 文件已被手动修改，跳过
                        println!("[SKIP] {} (modified by user)", file_name);
                    }
                } else {
                    println!("[SKIP] {} (not in lock)", file_name);
                }
            } else {
                let mut f = File::create(&file_path)?;
                f.write_all(content.as_bytes())?;
                println!("[CREATE] {}", file_name);
            }

            // 更新锁条目
            let relative_path = file_path.to_string_lossy().to_string();
            lock_entries.insert(relative_path, new_hash);

            mod_entries.push((current_prefix, false));
        }
    }
    Ok(())
}

/// 生成子命令列表的 all_commands 部分
fn generate_sub_all_commands(cmd: &CommandDef, indent: usize) -> String {
    let mut result = String::new();
    let indent_str = " ".repeat(indent);

    for sub in &cmd.subcommands {
        if sub.debug_only {
            result.push_str(&format!("{}#[cfg(debug_assertions)]\n", indent_str));
        }

        let struct_name = to_struct_name(&sub.name);
        result.push_str(&format!(
            "{}Arc::new({}::{}),\n",
            indent_str,
            sub.name.clone().into_safe(),
            struct_name
        ));
    }

    result
}

/// 收集所有预期的文件路径
fn collect_expected_files(cmds: &[CommandDef], base_dir: &Path, expected_files: &mut Vec<String>) {
    for cmd in cmds {
        if cmd.subcommands.is_empty() {
            let file_path = base_dir.join(format!("{}.rs", cmd.name));
            expected_files.push(file_path.to_string_lossy().to_string());
        } else {
            let sub_dir = base_dir.join(&cmd.name);
            let mod_rs_path = sub_dir.join("mod.rs");
            expected_files.push(mod_rs_path.to_string_lossy().to_string());
            collect_expected_files(&cmd.subcommands, &sub_dir, expected_files);
        }
    }
}

/// 清理不再需要的文件
fn cleanup_orphaned_files(
    lock_entries: &mut HashMap<String, u64>,
    expected_files: &[String],
) -> Result<(), Box<dyn std::error::Error>> {
    let orphaned: Vec<String> =
        lock_entries.keys().filter(|path| !expected_files.contains(path)).cloned().collect();

    for path in orphaned {
        let file_path = Path::new(&path);
        if file_path.exists() {
            // 验证文件哈希是否匹配
            if let Ok(content) = fs::read_to_string(file_path) {
                let current_hash = hash_content(&content);
                if let Some(stored_hash) = lock_entries.get(&path) {
                    if current_hash == *stored_hash {
                        fs::remove_file(file_path)?;
                        println!("[DELETE] {}", file_path.display());
                    } else {
                        println!("[SKIP] {} (modified by user, not deleted)", file_path.display());
                    }
                }
            }
        }
        lock_entries.remove(&path);
    }

    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();

    let yaml_path =
        Path::new(&manifest).parent().unwrap().parent().unwrap().join("cli-core").join("commands.yaml");
    println!("{}", yaml_path.display());

    if !yaml_path.exists() {
        eprintln!("❌ commands.yaml not found in current directory");
        std::process::exit(1);
    }

    let yaml = fs::read_to_string(&yaml_path)?;
    let config: Config = serde_yaml::from_str(&yaml)?;

    let out_dir = Path::new("./crates/cli-core/src/commands");
    if !out_dir.exists() {
        fs::create_dir_all(out_dir)?;
    }

    // 加载 lock 文件
    let lock_path = Path::new("./crates/cli-core/commands.lock");
    let mut lock_entries = read_lock_file(lock_path);

    let mut mod_entries = Vec::new();

    process_commands(&config.commands, out_dir, &mut mod_entries, "", &mut lock_entries)?;

    // 收集所有预期文件
    let mut expected_files = Vec::new();
    // 添加 mod.rs 到预期文件
    expected_files.push(out_dir.join("mod.rs").to_string_lossy().to_string());
    collect_expected_files(&config.commands, out_dir, &mut expected_files);

    // 为有子命令的命令添加 mod.rs
    for cmd in &config.commands {
        if !cmd.subcommands.is_empty() {
            let sub_dir = out_dir.join(&cmd.name);
            let mod_rs_path = sub_dir.join("mod.rs");
            expected_files.push(mod_rs_path.to_string_lossy().to_string());
        }
    }

    // 清理孤立文件
    cleanup_orphaned_files(&mut lock_entries, &expected_files)?;

    // 生成 mod.rs - 主入口
    let mut mod_rs = String::new();
    mod_rs.push_str(
        r#"use clap::ArgMatches;
use std::sync::Arc;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use std::sync::atomic::Ordering;
use crate::INTERRUPTED;

pub trait CommandExecutor {
    fn name(&self) -> &'static str;

    fn run(&self, matches: &ArgMatches) -> Result<()>;
}
"#,
    );

    // 生成顶级模块声明
    for (entry, _) in &mod_entries {
        let parts: Vec<&str> = entry.split("::").collect();

        if parts.len() == 1 {
            let cmd_name = &parts[0];

            fn find_cmd<'a>(cmds: &'a [CommandDef], name: &str) -> Option<&'a CommandDef> {
                cmds.iter().find(|c| c.name == name)
            }

            let cmd = find_cmd(&config.commands, cmd_name);

            if let Some(cmd) = cmd
                && cmd.debug_only
            {
                mod_rs.push_str("#[cfg(debug_assertions)]\n");
            }

            mod_rs.push_str(&format!("pub mod {};\n", cmd_name.to_string().into_safe()));
        }
    }

    mod_rs.push('\n');
    mod_rs.push_str("pub fn all_commands() -> Vec<Arc<dyn CommandExecutor>> {\n");
    mod_rs.push_str("    vec![\n");

    for (entry, _has_sub) in &mod_entries {
        if entry.contains("::") {
            continue;
        }

        let parts: Vec<&str> = entry.split("::").collect();
        let cmd_name = parts[parts.len() - 1];

        fn find_cmd<'a>(cmds: &'a [CommandDef], name: &str) -> Option<&'a CommandDef> {
            cmds.iter().find(|c| c.name == name)
        }

        let cmd = find_cmd(&config.commands, cmd_name);

        if let Some(cmd) = cmd
            && cmd.debug_only
        {
            mod_rs.push_str("        #[cfg(debug_assertions)]\n");
        }

        let struct_name = to_struct_name(cmd_name);
        mod_rs.push_str(&format!(
            "        Arc::new({}::{}),\n",
            cmd_name.to_string().into_safe(),
            struct_name
        ));
    }

    mod_rs.push_str("    ]\n");
    mod_rs.push_str("}\n");

    mod_rs.push_str(
        r#"
pub fn dispatch(matches: &ArgMatches) -> Result<()> {
    for cmd in all_commands() {
        if let Some(sub_matches) = matches.subcommand_matches(cmd.name()) {
            INTERRUPTED.store(false, Ordering::SeqCst);
            return cmd.run(sub_matches);
        }
    }
    eprintln!("No matching command found. Use --help for usage information.");
    Ok(())
}
"#,
    );

    // 使用 hash 校验决定是否写入 mod.rs
    let mod_rs_path = out_dir.join("mod.rs");
    if should_update_file(&mod_rs_path, &mod_rs, &lock_entries) {
        let mod_rs_hash = hash_content(&mod_rs);
        fs::write(&mod_rs_path, &mod_rs)?;
        println!("[UPDATE] mod.rs (top-level)");
        lock_entries.insert(mod_rs_path.to_string_lossy().to_string(), mod_rs_hash);
    } else {
        println!("[SKIP] mod.rs (top-level, already up-to-date)");
    }

    // 为有子命令的文件夹生成内部的 mod.rs
    for (entry, has_sub) in &mod_entries {
        if *has_sub {
            let parts: Vec<&str> = entry.split("::").collect();
            let dir_name = parts.last().unwrap();

            let mut dir_path = out_dir.to_path_buf();
            for part in &parts {
                dir_path = dir_path.join(part);
            }

            let mut sub_mod_rs = String::new();

            fn find_cmd_by_path<'a>(
                cmds: &'a [CommandDef],
                parts: &[&str],
            ) -> Option<&'a CommandDef> {
                if parts.is_empty() {
                    return None;
                }
                let cmd = cmds.iter().find(|c| c.name == parts[0])?;
                if parts.len() == 1 {
                    Some(cmd)
                } else {
                    find_cmd_by_path(&cmd.subcommands, &parts[1..])
                }
            }

            let cmd = find_cmd_by_path(&config.commands, &parts);

            if let Some(cmd) = cmd {
                sub_mod_rs.push_str("use clap::ArgMatches;\n");
                sub_mod_rs.push_str("use std::sync::Arc;\n");
                sub_mod_rs.push_str("#[allow(unused_imports)]\n");
                sub_mod_rs.push_str("use anyhow::{anyhow, Result};\n");
                sub_mod_rs.push_str("use crate::commands::CommandExecutor;\n");
                sub_mod_rs.push_str("use crate::INTERRUPTED;\n");
                sub_mod_rs.push_str("use std::sync::atomic::Ordering;\n\n");

                let parent_struct_name = to_struct_name(dir_name);
                sub_mod_rs.push_str(&format!(
                    r#"pub struct {parent_struct_name};

impl CommandExecutor for {parent_struct_name} {{
    fn name(&self) -> &'static str {{
        "{dir_name}"
    }}

    fn run(&self, matches: &ArgMatches) -> Result<()> {{
        dispatch(matches)
    }}
}}

"#,
                    parent_struct_name = parent_struct_name,
                    dir_name = dir_name,
                ));

                for sub in &cmd.subcommands {
                    if sub.debug_only {
                        sub_mod_rs.push_str("#[cfg(debug_assertions)]\n");
                    }

                    sub_mod_rs.push_str(&format!("pub mod {};\n", sub.name.clone().into_safe()));
                }

                sub_mod_rs.push_str(&format!(
                    r#"
pub fn all_commands() -> Vec<Arc<dyn CommandExecutor>> {{
    vec![
{}
    ]
}}

"#,
                    generate_sub_all_commands(cmd, 8)
                ));

                sub_mod_rs.push_str("pub fn dispatch(matches: &ArgMatches) -> Result<()> {\n");
                sub_mod_rs.push_str("    for cmd in all_commands() {\n");
                sub_mod_rs.push_str(
                    "        if let Some(sub_matches) = matches.subcommand_matches(cmd.name()) {\n",
                );
                sub_mod_rs.push_str("            INTERRUPTED.store(false, Ordering::SeqCst);\n");
                sub_mod_rs.push_str("            return cmd.run(sub_matches);\n");
                sub_mod_rs.push_str("        }\n");
                sub_mod_rs.push_str("    }\n");
                sub_mod_rs.push_str("    eprintln!(\"No matching command found. Use --help for usage information.\");\n");
                sub_mod_rs.push_str("    Ok(())\n");
                sub_mod_rs.push_str("}\n");
            }

            // 使用 hash 校验决定是否写入子 mod.rs
            let sub_mod_rs_path = dir_path.join("mod.rs");
            if should_update_file(&sub_mod_rs_path, &sub_mod_rs, &lock_entries) {
                let sub_mod_rs_hash = hash_content(&sub_mod_rs);
                fs::write(&sub_mod_rs_path, &sub_mod_rs)?;
                println!("[UPDATE] {}/mod.rs", dir_name);
                lock_entries.insert(sub_mod_rs_path.to_string_lossy().to_string(), sub_mod_rs_hash);
            } else {
                println!("[SKIP] {}/mod.rs (already up-to-date)", dir_name);
            }
        }
    }

    // 保存 lock 文件
    write_lock_file(lock_path, &lock_entries)?;
    println!("[SAVE] commands.lock");

    println!("\nDone! {} commands processed.", mod_entries.len());

    Ok(())
}
