// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// plugin.rs
// unload plugin
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct PluginCommand;

impl PluginCommand {
    /// `plugin_name` - Plugin to unload, required, value_name: PLUGIN_NAME
    #[allow(unused_variables)]
    pub fn execute(&self, plugin_name: String) -> Result<()> {
        // TODO: unload plugin
        println!("Command `plugin` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for PluginCommand {
    fn name(&self) -> &'static str {
        "plugin"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let plugin_name = matches
            .get_one::<String>("plugin_name")
            .ok_or_else(|| anyhow!("Missing required argument: plugin_name"))?
            .clone();
        self.execute(plugin_name)
    }
}
