// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;
use std::sync::Arc;
pub struct DeleteCommand;

impl CommandExecutor for DeleteCommand {
    fn name(&self) -> &'static str {
        "delete"
    }

    fn run(&self, matches: &ArgMatches) -> Result<()> {
        dispatch(matches)
    }
}

pub mod alias;
pub mod r#macro;

pub fn all_commands() -> Vec<Arc<dyn CommandExecutor>> {
    vec![Arc::new(alias::AliasCommand), Arc::new(r#macro::MacroCommand)]
}

pub fn dispatch(matches: &ArgMatches) -> Result<()> {
    for cmd in all_commands() {
        if let Some(sub_matches) = matches.subcommand_matches(cmd.name()) {
            return cmd.run(sub_matches);
        }
    }
    eprintln!("No matching command found. Use --help for usage information.");
    Ok(())
}
