// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// off.rs
// Turn off system proxy.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct OffCommand;

impl OffCommand {
    #[allow(unused_variables)]
    pub fn execute(&self) -> Result<()> {
        // TODO: Turn off system proxy.
        println!("Command `off` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for OffCommand {
    fn name(&self) -> &'static str {
        "off"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
