// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// download.rs
// Download plugin
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct DownloadCommand;

impl DownloadCommand {
    /// `plugin` - Plugin to download, required, value_name: PLUGIN
    /// `registry` - Set plugin registry
    /// `load` - load plugin after download
    /// `use_namespace` - load plugin and namespace after download, conflicts with: load
    #[allow(unused_variables)]
    fn execute(
        &self,
        plugin: String,
        registry: Option<String>,
        load: bool,
        use_namespace: bool,
    ) -> Result<()> {
        // TODO: Download plugin
        println!("Command `download` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for DownloadCommand {
    fn name(&self) -> &'static str {
        "download"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        let plugin = matches
            .get_one::<String>("plugin")
            .ok_or_else(|| anyhow!("Missing required argument: plugin"))?
            .clone();
        let registry = matches.get_one::<String>("registry").cloned();
        let load = matches.get_flag("load");
        let use_namespace = matches.get_flag("use_namespace");
        self.execute(plugin, registry, load, use_namespace)
    }
}
