// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// installed.rs
// show all installed plugins.
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct InstalledCommand;

impl InstalledCommand {
    #[allow(unused_variables)]
    pub fn execute(&self) -> Result<()> {
        // TODO: show all installed plugins.
        println!("Command `installed` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for InstalledCommand {
    fn name(&self) -> &'static str {
        "installed"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
