// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// downloaded.rs
// show all downloaded plugins.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct DownloadedCommand;

impl DownloadedCommand {
    #[allow(unused_variables)]
    pub fn execute(&self) -> Result<()> {
        // TODO: show all downloaded plugins.
        println!("Command `downloaded` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for DownloadedCommand {
    fn name(&self) -> &'static str {
        "downloaded"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
