// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// loaded.rs
// show all loaded plugins.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct LoadedCommand;

impl LoadedCommand {
    #[allow(unused_variables)]
    fn execute(&self) -> Result<()> {
        // TODO: show all loaded plugins.
        println!("Command `loaded` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for LoadedCommand {
    fn name(&self) -> &'static str {
        "loaded"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
