// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// updates.rs
// Show all avaliable updates.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct UpdatesCommand;

impl UpdatesCommand {
    #[allow(unused_variables)]
    fn execute(&self) -> Result<()> {
        // TODO: Show all avaliable updates.
        println!("Command `updates` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for UpdatesCommand {
    fn name(&self) -> &'static str {
        "updates"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
