[package]
name = "yaml2cmd"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "yaml2cmd"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
