[package]
name = "cli-standard"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = { workspace = true }
anyhow = { workspace = true }
humantime = "2.1"
rpassword = "7.5.4"
which = "8.0.5"
shell-words = "1.1.1"
safer-ffi = { workspace = true }
cli-core-types = { workspace = true }
libloading = { workspace = true }

[build-dependencies]
yaml2cmd-build = { workspace = true }

[lints]
workspace = true
