// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// active_users.rs
// Show active users in current frequency
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct ActiveUsersCommand;

impl ActiveUsersCommand {
    #[allow(unused_variables)]
    fn execute(&self) -> Result<()> {
        // TODO: Show active users in current frequency
        println!("Command `active_users` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for ActiveUsersCommand {
    fn name(&self) -> &'static str {
        "active_users"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
