// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// moderators.rs
// Show moderators in current frequency
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct ModeratorsCommand;

impl ModeratorsCommand {
    #[allow(unused_variables)]
    pub fn execute(&self) -> Result<()> {
        // TODO: Show moderators in current frequency
        println!("Command `moderators` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for ModeratorsCommand {
    fn name(&self) -> &'static str {
        "moderators"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
