// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// options.rs
// Show available set/setg options
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct OptionsCommand;

impl OptionsCommand {
    #[allow(unused_variables)]
    pub fn execute(&self) -> Result<()> {
        // TODO: Show available set/setg options
        println!("Command `options` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for OptionsCommand {
    fn name(&self) -> &'static str {
        "options"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
