// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// export.rs
// Export workspace information to a file. Default: current workspace.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct ExportCommand;

impl ExportCommand {
    /// `workspace_name` - workspace name.
    /// `output` - workspace output file. Default: <PROGRAM_DIR>/workspaces/<WORKSPACE_NAME>.toml 
    #[allow(unused_variables)]
	pub fn execute(&self, workspace_name: Option<String>, output: Option<String>) -> Result<()> {
		// TODO: Export workspace information to a file. Default: current workspace.
		println!("Command `export` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for ExportCommand {
	fn name(&self) -> &'static str {
		"export"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        let workspace_name = matches
            .get_one::<String>("workspace_name")
            .cloned();
        let output = matches
            .get_one::<String>("output")
            .cloned();
        self.execute(workspace_name, output)
	}
}
