// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// rename.rs
// Rename a workspace. Default: current workspace
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct RenameCommand;

impl RenameCommand {
    /// `source` - Original workspace name.
    /// `target` - Final workspace name., required
    #[allow(unused_variables)]
	pub fn execute(&self, source: Option<String>, target: String) -> Result<()> {
		// TODO: Rename a workspace. Default: current workspace
		println!("Command `rename` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for RenameCommand {
	fn name(&self) -> &'static str {
		"rename"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        let source = matches
            .get_one::<String>("source")
            .cloned();
        let target = matches
            .get_one::<String>("target")
            .ok_or_else(|| anyhow!("Missing required argument: target"))?
            .clone();
        self.execute(source, target)
	}
}
