// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// show.rs
// Show information for a certain workspace. Default: current workspace.
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct ShowCommand;

impl ShowCommand {
    /// `workspace_name` - workspace name., value_name: WORKSPACE_NAME
    #[allow(unused_variables)]
	pub fn execute(&self, workspace_name: Option<String>) -> Result<()> {
		// TODO: Show information for a certain workspace. Default: current workspace.
		println!("Command `show` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for ShowCommand {
	fn name(&self) -> &'static str {
		"show"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        let workspace_name = matches
            .get_one::<String>("workspace_name")
            .cloned();
        self.execute(workspace_name)
	}
}
