// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// active_freqs.rs
// Show all active frequencies
#[allow(unused_imports)]
use crate::INTERRUPTED;
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{anyhow, Result};
use clap::ArgMatches;

pub struct ActiveFreqsCommand;

impl ActiveFreqsCommand {
    #[allow(unused_variables)]
	pub fn execute(&self) -> Result<()> {
		// TODO: Show all active frequencies
		println!("Command `active_freqs` is not yet implemented.");
		Ok(())
	}
}

impl CommandExecutor for ActiveFreqsCommand {
	fn name(&self) -> &'static str {
		"active_freqs"
	}

	#[allow(unused_variables)]
	fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
	}
}
