// NOT-MODIFIED-TAG: AUTO @generated BY CMD-GEN. IF YOU MODIFIED THIS FILE, PLEASE DELETED THE TAG.
// locals.rs
// Show value of all local variables
use crate::commands::CommandExecutor;
#[allow(unused_imports)]
use anyhow::{Result, anyhow};
use clap::ArgMatches;

pub struct LocalsCommand;

impl LocalsCommand {
    #[allow(unused_variables)]
    pub fn execute(&self) -> Result<()> {
        // TODO: Show value of all local variables
        println!("Command `locals` is not yet implemented.");
        Ok(())
    }
}

impl CommandExecutor for LocalsCommand {
    fn name(&self) -> &'static str {
        "locals"
    }

    #[allow(unused_variables)]
    fn run(&self, matches: &ArgMatches) -> Result<()> {
        self.execute()
    }
}
